export const organiserConfig = {
  organisers: [
    {
      id: 1,
      name: "Name",
      title: "title",
      image: "/images/organisers/demo_organisers.png",
      imagePosition: "center",
      alt: "Hackatron Hackathon Organisers",
      twitter: "https://twitter.com",
      linkedin: "https://www.linkedin.com",
    },
    {
      id: 2,
      name: "Name",
      title: "title",
      image: "/images/organisers/demo_organisers.png",
      imagePosition: "center",
      alt: "Hackatron Hackathon Organisers",
      twitter: "https://twitter.com",
      linkedin: "https://www.linkedin.com",
    },
    {
      id: 3,
      name: "Name",
      title: "title",
      image: "/images/organisers/demo_organisers.png",
      imagePosition: "center",
      alt: "Hackatron Hackathon Organisers",
      twitter: "https://twitter.com",
      linkedin: "https://www.linkedin.com",
    },
    {
      id: 4,
      name: "Name",
      title: "title",
      image: "/images/organisers/demo_organisers.png",
      imagePosition: "center",
      alt: "Hackatron Hackathon Organisers",
      twitter: "https://twitter.com",
      linkedin: "https://www.linkedin.com",
    },
    {
      id: 5,
      name: "Name",
      title: "title",
      image: "/images/organisers/demo_organisers.png",
      imagePosition: "center",
      alt: "Hackatron Hackathon Organisers",
      twitter: "https://twitter.com",
      linkedin: "https://www.linkedin.com",
    },
    {
      id: 6,
      name: "Name",
      title: "title",
      image: "/images/organisers/demo_organisers.png",
      imagePosition: "center",
      alt: "Hackatron Hackathon Organisers",
      twitter: "https://twitter.com",
      linkedin: "https://www.linkedin.com",
    },
  ],
  coreTeam: [
    {
      href: "#",
      name: "Name 1",
      title: "Graphics Team",
      image: "/images/CoreTeam/demo_core.png",
    },
    {
      href: "https://www.linkedin.com/",
      name: "Name 2",
      title: "PR & Social Media Team",
      image: "/images/CoreTeam/demo_core.png",
    },
    {
      href: "https://www.linkedin.com/",
      name: "Name 3",
      title: "PR & Social Media Team",
      image: "/images/CoreTeam/demo_core.png",
    },
  ],
};
