export const scheduleConfig = {
  data: [
    {
      Day: "Day-1",
      Date: "13th April 2025",
      TimeCont: [
        {
          id: "1",
          Direction: "left",
          Img: "./images/schedule/sun.svg",
          Time: "8:00 AM ",
          Description: "Registration, Inauguration, Breakfast",
        },
        {
          id: "2",
          Direction: "right",
          Img: "./images/schedule/mercury.svg",
          Time: "10:00 AM ",
          Description: "Coding Begins",
        },
        {
          id: "3",
          Direction: "left",
          Img: "./images/schedule/venus.svg",
          Time: "1:00 PM ",
          Description: "Lunch Break",
        },
        {
          id: "4",
          Direction: "right",
          Img: "./images/schedule/earth.svg",
          Time: "2:00 PM ",
          Description: "Coding Continues",
        },
        {
          id: "5",
          Direction: "left",
          Img: "./images/schedule/mars.svg",
          Time: "6:00 PM ",
          Description: "Snack & Networking",
        },
        {
          id: "6",
          Direction: "right",
          Img: "./images/schedule/jupiter.svg",
          Time: "7:00 PM",
          Description: "First Round of Judging",
        },
        {
          id: "7",
          Direction: "left",
          Img: "./images/schedule/saturn.svg",
          Time: "9:00 PM",
          Description: "Dinner & Chill",
        },
        {
          id: "8",
          Direction: "right",
          Img: "./images/schedule/uranus.svg",
          Time: "11:00 PM",
          Description: "Coding Continues",
        },
      ],
    },
    {
      Day: "Day-2",
      Date: "14th April 2025",
      TimeCont: [
        {
          id: "9",
          Direction: "left",
          Img: "./images/schedule/neptune.svg",
          Time: "9:00 AM",
          Description: "Breakfast",
        },
        {
          id: "10",
          Direction: "right",
          Img: "./images/schedule/mercury.svg",
          Time: "10:00 AM",
          Description: "Coding Continues",
        },
        {
          id: "11",
          Direction: "left",
          Img: "./images/schedule/venus.svg",
          Time: "11:00 AM",
          Description: "Second Round Judging",
        },
        {
          id: "12",
          Direction: "right",
          Img: "./images/schedule/earth.svg",
          Time: "1:00 PM",
          Description: "Lunch Break",
        },
        {
          id: "13",
          Direction: "left",
          Img: "./images/schedule/mars.svg",
          Time: "2:30 PM",
          Description: "Last Coding Sprint",
        },
        {
          id: "14",
          Direction: "right",
          Img: "./images/schedule/jupiter.svg",
          Time: "6:00 PM",
          Description: "Snack Break",
        },
        {
          id: "15",
          Direction: "left",
          Img: "./images/schedule/saturn.svg",
          Time: "7:00 PM",
          Description: "Final Judging Round",
        },
        {
          id: "16",
          Direction: "right",
          Img: "./images/schedule/uranus.svg",
          Time: "8:00 PM",
          Description: "Dinner",
        },
        {
          id: "17",
          Direction: "left",
          Img: "./images/schedule/neptune.svg",
          Time: "9:00 PM Onwards",
          Description: "Winners Announcement",
        },
      ],
    },
  ],
};