export const SpeakerConfig = [
  {
    id: 1,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 2,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 3,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 4,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 5,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 6,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 7,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 8,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 9,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 10,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },
  {
    id: 11,
    linkedin: "https://www.linkedin.com/in/anuj-bag",
    twitter: "#",
    name: "Anuj Bag",
    title: "SDE III",
    image: "/images/home/Frame 96.png",
  },

];
